# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFCYLKPOeSNwMDtQJ52qwCoQU5araCpJ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df_q1= pd.read_csv('/content/drive/MyDrive/Energy_project/renewable Q1.csv')
df_q2= pd.read_csv('/content/drive/MyDrive/Energy_project/renewable Q2.csv')

display(df_q1.head())
display(df_q2.head())

df_q1.info()
df_q2.info()

display(df_q1.describe())
display(df_q2.describe())

print("Q1 missing values:\n", df_q1.isnull().sum())
print("Q2 missing values:\n", df_q2.isnull().sum())

def clean_cols(df):
  df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')
  return df
df_q1= clean_cols(df_q1)
df_q2= clean_cols(df_q2)

print(df_q1.columns.tolist())
print(df_q2.columns.tolist())

df= pd.concat([df_q1, df_q2], axis=0, ignore_index=True)
print("Merged dataframe shape:", df.shape)

df.info()
print(df.isnull().sum())
display(df.head())

plt.figure(figsize=(8,5))
sns.countplot(
    data=df,
    x='type',
    order=df['type'].value_counts().index
)
plt.xticks(rotation=45)
plt.title('Number of projects by energy type (Q1+Q2 2025)')
plt.show()

df['type'].value_counts()

capacity_by_tender = df.groupby('tendering_year')['capacity_gw'].sum().reset_index()
plt.figure(figsize=(8,5))
sns.barplot(
    data=capacity_by_tender,
    x='tendering_year',
    y='capacity_gw'
)
plt.title('Total Installed Capacity by Tendeering Year')
plt.xlabel('Tendering Year')
plt.ylabel('Capacity (Gw)')
plt.show()

capacity_by_tender= df.groupby('expected_commissioning_year')['capacity_gw'].sum().reset_index()
plt.figure(figsize=(8,5))
sns.barplot(
    data=capacity_by_tender,
    x='expected_commissioning_year',
    y= 'capacity_gw'
)
plt.title('Total Installed Capacity By Commissioning Year')
plt.xlabel('Commissioning Year')
plt.ylabel('Capacity (Gw)')
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(data=df,x='region',order=df['region'].value_counts().index)
plt.xticks(rotation=45)
plt.title('Projects By Region (Q1+Q2 2025)')
plt.show()



"""Key Insights

*Projects by Energy Type:* Most renewable energy projects in Q1 and Q2 2025 are solar (70 projects), while wind projects account for a smaller share (10 projects). This highlights Saudi Arabia's strategic focus on solar energy.

*Tendering Year:* The highest project tendering activity occurred in 2024 (40 projects), followed by 2023 (16 projects), reflecting focused planning in these years.

*Expected Commissioning Year:* The largest capacity is expected to come online in 2028 (35 GW), indicating a peak in production. Other years have smaller, relatively similar capacities.

*Projects by Region:* Makkah hosts the most projects (20 projects), while other regions are relatively balanced in distribution.<br>
_______<br>

# النتائج الرئيسية

*المشاريع حسب نوع الطاقة:* معظم مشاريع الطاقة المتجددة للربع الأول والثاني من 2025 هي مشاريع شمسية بعدد 70 مشروعًا، بينما مشاريع الرياح تمثل حصة أصغر بعدد 10 مشاريع. يشير ذلك إلى تركيز المملكة الاستراتيجي على الطاقة الشمسية.

*سنة الطرح (Tendering Year):* أعلى نشاط في طرح المشاريع كان في 2024 (40 مشروعًا)، يليه 2023 (16 مشروعًا)، مما يعكس تركيز المملكة على التخطيط في هذه السنوات.

*سنة التشغيل المتوقع (Expected Commissioning Year):* من المتوقع أن تدخل أكبر كمية من القدرة الكهربائية للخدمة في 2028 (35 جيجاوات)، ما يشير إلى ذروة الإنتاج. باقي السنوات تمتلك قدرات أقل ومتقاربة نسبيًا.

*المشاريع حسب المناطق:* تستضيف منطقة مكة أكبر عدد من المشاريع بعدد 20 مشروعًا، بينما بقية المناطق موزعة بشكل متوازن نسبيًا
"""
